name: pre-build

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  pre-build:
    # Name the Job
    name: Pre-Build
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      # Runs the Super-Linter action
      - name: Style check
        run: |
          pip install flake8
          python -m flake8 .
      - name: Build Docs
        run: |
          cd doc
          python -m pip install -r requirements.txt
          make html SPHINXOPTS='-W -v'

